=== LivePersonInc/lp-rich-content-validator/src/schemas/gbm/bodies/carousel/gbmCarouselCardCompact.json
{
  "title": "gbmCarouselCardCompact",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": ["type", "elements", "tag", "display"],
  "properties": {
    "type": {
      "type": "string",
      "enum": ["vertical", "horizontal"],
      "default": "vertical",
      "readonly": true
    },
    "alt": {
      "minLength": 1,
      "maxLength": 2000,
      "type": "string"
    },
    "tag": {
      "type": "string",
      "enum": ["generic"],
      "default": "generic",
      "readonly": true
    },
    "display": {
      "$ref": "gbmDisplaySettingsCompact.json"
    },
    "elements": {
      "anyOf": [
        { "$ref": "gbmCardElementOrder1.json" },
        { "$ref": "gbmCardElementOrder2.json" },
        { "$ref": "gbmCardElementOrder3.json" },
        { "$ref": "gbmCardElementOrder4.json" },
        { "$ref": "gbmCardElementOrder5.json" },
        { "$ref": "gbmCardElementOrder6.json" },
        { "$ref": "gbmCardElementOrder7.json" }
      ]
    }
  }
}

=== LivePersonInc/lp-rich-content-validator/tests/helper/gbm/richCards/json/displayCompact.json
{
  "type": "vertical",
  "tag": "generic",
  "display": {
    "size": "compact"
  },
  "elements": [
    {
      "type": "image",
      "url": "https://www.google.com/images/errors/robot.png"
    },
    {
      "type": "text",
      "tag": "title",
      "text": "IPhone 8",
      "tooltip": "brand new iphone 8"
    },
    {
      "type": "text",
      "text": "$155.99",
      "tooltip": "155.99"
    },
    {
      "type": "button",
      "title": "btn1",
      "click": {
        "actions": [
          {
            "type": "publishText",
            "text": "btn01"
          }
        ]
      }
    },
    {
      "type": "button",
      "title": "btn2",
      "click": {
        "actions": [
          {
            "type": "publishText",
            "text": "btn02"
          }
        ]
      }
    },
    {
      "type": "button",
      "title": "btn3",
      "click": {
        "actions": [
          {
            "type": "publishText",
            "text": "btn03"
          }
        ]
      }
    }
  ]
}
